set SDKROOT=d:\sdks
set VS_ROOT=d:\vs2010
set VS_VC_ROOT=%VS_ROOT%\VC

set PATH_SDK_WIN32SDK=%SDKROOT%
set PATH_SDK_WINPSDK=%SDKROOT%
set PATH_SDK_WINSDK=%SDKROOT%
set PATH_TOOL_VCC70=%SDKROOT%	
set PATH_TOOL_VCC80AMD64=%SDKROOT%
set PATH_SDK_WINPSDK71=%SDKROOT%
set PATH_TOOL_VCC100AMD64=%VS_VC_ROOT%
set PATH_TOOL_VCC70_LIB=D:\vs2010\VC\lib
set PATH_SDK_WINPSDK71_LIB=D:\sdks\lib\amd64
set PATH_TOOL_VCC80AMD64_LIB=D:\vs2010\VC\lib\amd64
set PATH_TOOL_VCC100AMD64_LIB=D:\vs2010\VC\lib\amd64
set PATH_TOOL_VCC100_LIB=D:\vs2010\VC\lib\amd64

set SDKLIB=d:\sdks\lib\amd64
set PATH_SDK_WIN32SDK_LIB=%SDKLIB%
set PATH_SDK_WIN32SDK2002_LIB=%SDKLIB%
set PATH_SDK_WIN64SDK_LIB=%SDKLIB%
set PATH_SDK_WINPSDK_LIB=%SDKLIB%
set PATH_SDK_WINPSDK71_LIB=%SDKLIB%